import type { Message } from './message';

/**
 * One conversation in Kunnskapsassistenten. The design calls it «tråd»,
 * «samtale» and «chat» interchangeably; the code says thread throughout.
 *
 * `conversationId` is deliberately separate from `id`. The backend has two
 * conversation concepts that do not meet: a `conversation_id` created by
 * `tools/call` is not visible through `/api/conversations`. `id` is our own
 * thread key and the one in the route `/threads/:threadId`.
 * See design/eksisterende/api-for-frontend.md, gap 4.
 */
export interface Thread {
  id: string;
  /** Autogenerated from the first question when the user names nothing. */
  title: string;
  /** ISO 8601. The backend returns epoch milliseconds; the client normalises. */
  createdAt: string;
  /**
   * ISO 8601. Drives the grouping in the thread list: «I dag», «Siste 7
   * dager», «Siste 30 dager», then month names, then the year (answer 6).
   */
  updatedAt: string;
  /** The backend conversation to continue on the next turn. */
  conversationId?: string;
}

/** A thread with its messages, the shape a thread route needs. */
export interface ThreadDetail extends Thread {
  messages: Message[];
}
